### PR TITLE
Refactor inspector and fix repo path

### LINKED ISSUE #154: Bug: if the pom.xml is not at the root of the directory it could lead to errors
There is a confusion between repo path and maven module path in the code. Then in `AbstractStep#testPomLocation` the inspector repoLocalPath could be changed leading to errors when doing git manipulation:

```
18:06:06.062 [main] ERROR f.i.s.r.p.step.SquashRepository - Error while committing (and/or pushing) new repairnator information. 
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /root/workspace/geoserver/geoserver/213800779/src
```

### PR DESCRIPTION
**Pull request by surli**
This PR intends to fix #154 and to refactor repairnator-pipeline in order to remove some stuff from `ProjectInspector`:
  - move some steps in their own package
  - create a JobStatus class to deal with dynamic properties of the job 
  - create a field in JobStatus to manage the path of the main pom.xml file (fix #154)

### CODE REVIEW

**Comment by surli** [comment]
@fermadeiral could you review this one?

**Comment by fermadeiral** [comment]
> @fermadeiral could you review this one?

Ok ;-)

File: repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java [hunk 1]
```diff
@@ -1,7 +1,8 @@
-package fr.inria.spirals.repairnator.process.step;
+package fr.inria.spirals.repairnator.process.step.gatherinfocontract;
```
Comment (fermadeiral) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: I think that the name of the package should be changed, maybe to "testinformation".

File: repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java [hunk 2]
```diff
@@ -34,23 +35,16 @@
     private Set<FailureLocation> failureLocations;
     private Set<String> failureNames;
     private String failingModulePath;
+    private boolean skipSettingStatusInformation;
 
     private ContractForGatherTestInformation contract;
 
-    public GatherTestInformation(ProjectInspector inspector, ContractForGatherTestInformation contract) {
+    public GatherTestInformation(ProjectInspector inspector, ContractForGatherTestInformation contract, boolean skipSettingStatusInformation) {
```
Comment (fermadeiral) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: Based on the way you instantiate GatherTestInformation in the inspectors, it seems that there is a correlation between `skipSettingStatusInformation` and the contracts `BuildShouldPass` and `BuildShouldFail`. If that is true, maybe a javadoc would be nice here.

File: repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java (hunk 1 above)
Comment (surli) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: Ok to change but I'd go more for sthg like `gatherinfo`: it's the step so should be an action, not the result.

Comment (fermadeiral) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: Great.

File: repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java (hunk 2 above)
Comment (surli) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: In fact this one is really for you to avoid putting in JobStatus wrong information. So maybe it's enough to put it in the contract, I really don't know. Tell me :)

Comment (fermadeiral) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: I agreed with what you did: `skipSettingStatusInformation` must be false when `BuildShouldFail`, because this is the scenario both of us want to save information. I don't see any better way to implement it now, but what I meant is that we should put some javadoc in the code explaining this correlation.

Comment (surli) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: Ok, so I keep the boolean argument, in case this correlation is not true anymore and I explain its goal, right?

Comment (fermadeiral) [inline repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfocontract/GatherTestInformation.java]: I think it is ok for now.
